apiVersion: v1
kind: ServiceAccount
metadata:
  name: gtp5g-driver-container
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gtp5g-driver-container
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gtp5g-driver-container
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gtp5g-driver-container
subjects:
- kind: ServiceAccount
  name: gtp5g-driver-container
userNames:
- system:serviceaccount:gtp5g-demo:gtp5g-driver-container
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gtp5g-driver-container
spec:
  selector:
    matchLabels:
      app: gtp5g-driver-container
  template:
    metadata:
      labels:
        app: gtp5g-driver-container
    spec:
      serviceAccount: gtp5g-driver-container
      serviceAccountName: gtp5g-driver-container
      containers:
      - image: quay.io/ferossi/gtp5g-mod-ocp:v4.8
        name: gtp5g-driver-container
        imagePullPolicy: Always
        command: ["/root/entrypoint.sh"]
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/", "rmmod", "gtp5g"]        
        securityContext:
          privileged: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
